name: Release Dev

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

env:
  NPM_TOKEN: ${{secrets.NPM_TOKEN}}
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
  AWS_REGION: ${{secrets.AWS_REGION}}
  CI: true
  APP_STAGE: 'development'
  GH_PAT: ${{ secrets.GH_PAT }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release-dev:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Build Storybook
        run: |
          yarn build:storybook

      - name: Deploy
        run: |
          yarn deploy
